lowRISC/ot-sca

cw/cw305/capture.yaml, cw/cw305/capture_traces.py, cw/cw305/util/device.py, cw/cw305/util/spiflash.py, doc/getting_started.md
* Make spiflash configuratble from capture.yaml.
* Add FTDI connectivity instructions to the doc/getting_started.md
guide.
Signed-off-by: Miguel Osorio <miguelosorio@google.com>
=> Add configuration options for spiflash

.gitignore, python-requirements.txt
This PR fixes the Python requirements to use upstream ChipWhisperer toolchain from GitHub as required for #8.
I will have to rebase this one, once #8 has been merged.
=> Fix python requirements

python-requirements.txt, util/cw_to_trs.py
The script is based on Riscures trsfile Python library. Use the script
to convert traces stored in ChipWhisperer's project to Riscure's trs
format.
Signed-off-by: Miguel Osorio <miguelosorio@google.com>
=> Add ChipWhisperer to trs trace conversion script.

cw/cw305/capture.yaml, cw/cw305/simple_capture_traces.py, cw/cw305/util/device.py
This PR slightly reworks how the simple capture scripts handles cases where the ADC might saturate. Previously it just silently skipped failed captures. Now, the trace is recorded anyway. But when plotting the recorded traces, all traces are checked for samples outside a safe range and a warning is printed in that case. The user is suggested to reduce the scope gain. This allows to keep the capture script simple but gives an easy way to verify the setup before triggering a long capture run.
Also, a configurable delay is added before the capture start in order to unplug the FTDI cable to reduce noise.
This PR supersedes #21 .
=> Rework simple capture

cw/cw305/objs/aes_serial_fpga_nexysvideo.bin, cw/cw305/objs/lowrisc_systems_top_earlgrey_cw305_0.1.bit, cw/cw305/simple_capture_traces.py, cw/cw305/util/device.py, cw/cw305/util/spiflash.py, python-requirements.txt
This PR implements support for programming OpenTitan over the SPI interface of SAM3U on CW305 and includes the following commits:
* [objs] Update bitstream to remove dependencies for programming
* [objs] Update aes_serial binary
* Add pycryptodome to python dependencies
* ~Remove trace filtering based on min value~
* Remove unused constant
* Implement support for programming OpenTitan using SAM3U on CW305
It would be great if you could checkout this PR and let me know if you run into any issues. I left the current spiflash based programmer intact just in case. I can remove it if the new implementation is reliable enough. 
Closes #15.
=> Implement support for programming OpenTitan using SAM3U on CW305

util/cw_to_trs.py
This change adds a progress bar and an informational message to indicate
the status of the conversion process. This change also modifies the
`--export-key` argument so that it doesn't expect a `True` or `False`
value.
Signed-off-by: Alphan Ulusoy <alphan@google.com>
=> Minor updates to cw_to_trs.py

cw/cw305/util/spiflash.py
This change updates _Bootstrap.transfer to work with the recent changes in
chipwhisperer (newaetech/chipwhisperer@68f12e1).
Signed-off-by: Alphan Ulusoy <alphan@google.com>
=> Update spiflash._Bootstrap.transfer in response to changes in chipwhisperer

cw/cw305/correlation-enhanced_collision_attack.py
The number of samples used for computing the average traces was erroneously hardcoded.
=> Allow changing #samples used for correlation-enhanced collision attack

cw/cw305/ceca.py, python-requirements.txt
This PR adds a distributed implementation of the correlation-enhanced power analysis collision attack described in "Correlation-Enhanced Power Analysis Collision Attack" by A. Moradi, O. Mischke, and T. Eisenbarth (https://eprint.iacr.org/2010/297.pdf).
In addition to using Ray (https://docs.ray.io/en/master/index.html) for distributed computation, this implementation also uses a modified version of Dijkstra's shortest path algorithm to utilize all available information on differences between key bytes. This implementation also optimizes several operations for improved performance, e.g. various `numpy` operations and encrypting with multiple keys in parallel using `scared` to check if the attack was successful, etc.
I get the following numbers when I run this on my workstation (12 cores @ …
=> Add a distributed implementation of the correlation-enhanced collision attack

.dockerignore, doc/getting_started.md, util/docker/Dockerfile, util/docker/build_image.sh, util/docker/docker_entrypoint.sh, util/docker/run_container.sh
This change adds a Dockerfile and supporting scripts to build a ready-to-use OpenTitan SCA(/FI) image.
Some details worth mentioning:
* The image includes a python virtual environment. While this is not strictly necessary, it decouples our dependencies from the base image and gives us more freedom.
* `run_container.sh` adds ChipWhisperer USB devices into the container. Thus, this image can be used for capturing traces in addition to running ot-sca python code.
* Special care has been taken to avoid permission issues: The image creates a new user at runtime with a UID and a GID that matches the UID and GID of the owner of the host directory.
* It is possible to run `pip install` in the container if an in-progress change adds a new python dependency.
* The image also includes `git-lfs` so …
=> [docker] Add Dockerfile and supporting scripts

cw/cw305/capture.yaml, cw/cw305/simple_capture_traces_waverunner.py, cw/cw305/waverunner.py, python-requirements.txt
This change adds support for capturing traces using a LeCroy WaveRunner 9104 and a new script that captures traces using the new 'b' (batch encrypt) command.
As I mentioned earlier, WaveRunner has several settings that we should evaluate. For the sake of simplicity, most of the parameters are hardcoded for now in `waverunner.py`. I thought it would be better to postpone the decision on which parameters should be fixed and which should be tunable when we start working on the CLI (and the refactoring that will go with it). I guess the most important parameters are sampling rate and noise filtering which are set to 1 GS/s down to 100 MS/s with 10x sparsing + 2.5bits ERes (enhanced resolution, i.e. noise filtering). 2.5bits ERes is a bit extreme and significantly reduces the bandwidth (-3dB @ …
=> Add WaveRunner support and batch capture script

cw/cw305/util/device.py
We currently don't force reprogramming the FPGA on CW305 if it's already programmed. This is fine except when you have a bitstream and forget about this behavior (like me). This change prints a more accurate message indicating whether the FPGA was actually programmed or not.
=> Patch fpga.FPGAProgram at runtime to detect if the FPGA was actually programmed

cw/cw305/simple_capture_traces.py, cw/cw305/simple_capture_traces_waverunner.py
This is related to #24 and doesn't fix the underlying issue (I'm still not sure what it is, could be the `flush` after setting the baudrate in `initialize_target` or something else) but I thought it would be a good idea to wait until receiving a proper response from the target before starting the capture.
=> Ping target with 'v' until it responds.

cw/cw305/objs/aes_serial_fpga_nexysvideo.bin, cw/cw305/objs/lowrisc_systems_top_earlgrey_cw305_0.1.bit, cw/cw305/simple_capture_traces.py, cw/cw305/util/device.py, cw/cw305/waverunner.py
This change updates the FPGA bitstream and `aes_serial` binary. Since I wasn't able to generate the bitstream from the tip (lowRISC/opentitan@445fe3132), both files were built by cherry-picking the relevant `aes_serial` updates (lowRISC/opentitan@675e9497b and lowRISC/opentitan@cbbc70fe2) on top of lowRISC/opentitan@71d98f8e (last known good commit).
This change also
* Removes acks during capture (see cw/cw305/simple_capture_traces.py) and adjusts the scope gain in cw/cw305/util/device.py (not sure if the new value will be the best for everyone).
* Adjusts the vertical scale and the trigger offset of waverunner.
Here's how the traces look (top: chipwhisperer, bottom: waverunner):
I also verified that all capture scripts work with the new binaries and we can recover the key (tried only …
=> Update FPGA bitstream and aes_serial binary

cw/cw305/capture.yaml, cw/cw305/cw_lite_segmented.py, cw/cw305/simple_capture_traces_batch.py, cw/cw305/waverunner.py
This change adds ChipWhisperer-Lite support for batch captures, i.e. captures that use the 'b' (batch encrypt) command.
Capturing 10000 traces at ~870 traces/s:
```
$ ./simple_capture_traces_batch.py -s cw_lite
Connecting and loading FPGA... SKIPPED! (see: /repo/cw/cw305/util/device.py:initialize_fpga)
Initializing PLL1
Programming OpenTitan with "objs/aes_serial_fpga_nexysvideo.bin"...
Transferring frame 0x00000000 @ 0x00000000.
Transferring frame 0x00000001 @ 0x000007D8.
Transferring frame 0x00000002 @ 0x00000FB0.
Transferring frame 0x00000003 @ 0x00001788.
Transferring frame 0x00000004 @ 0x00001F60.
Transferring frame 0x00000005 @ 0x00002738.
Transferring frame 0x80000006 @ 0x00002F10.
Serial baud rate = 38400
Serial baud rate = 115200
Scope setup with sampling rate 100003074.0 S/s …
```
=> Add ChipWhisperer-Lite support for batch captures

cw/cw305/simple_capture_traces_batch.py
This PR contains two commits in order to increase the capture rate for long batch captures.
1. Frequent storage segment array resizing is avoided by setting the hint value to the known storage segment size (a project parameter).
2. During capture, `disable` all except for the latest two storage segments to keep the run time of the `append()` function approximately constant. By default, it increases linearly with the number of traces captured.
With these changes it is possible to maintain high capture rates up to millions of traces. Further changes are probably needed to avoid memory limitations. Currently everything is kept in memory during a capture and traces are written to disk only at the very end. I've opened an issue newaetech/chipwhisperer#344 in the hope of getting some further …
=> Maintain high capture rate for long batch captures

python-requirements.txt
Currently, we get the latest chipwhisperer version whenever we `pip install`. This change adds a commit hash for chipwhisperer to the requirements file to give us more control over updating chipwhisperer versions.
@vogelpi and I spent a quite bit of time today to recover from an upstream change that breaks segmented captures using cw-lite on our setup. We were able to identify the following working combination:
* Chipwhisperer commit: newaetech/chipwhisperer@099807207f3351d16e7988d8f0cccf6d570f306a
* Chipwhisperer-lite firmware version: 0.23 (probably added in newaetech/chipwhisperer@f904ad556b692ea22ec54f1bde8628c7e31a0944 or the commit before that) This is older than the firmware in the chipwhisperer repo but we can identify a more recent working version later and update the hash in the …
=> Pin chipwhisperer version in the requirements file

cw/cw305/ceca.py
This number is a actually a far more relevant indicator for the amount of leakage in the traces than successful key recovery (pass/fail). Therefore, this PR adds the functionality to compute this number and report it on the command line.
This solves #30 .
=> [ceca] Report number of correctly guessed key byte differences

.gitattributes, cw/cw305/capture_aes.yaml, cw/cw305/capture_sha3.yaml, cw/cw305/mix_columns_capture.py, cw/cw305/objs/aes_serial_fpga_cw310.bin, cw/cw305/objs/lowrisc_systems_chip_earlgrey_cw310_0.1.bit, cw/cw305/objs/sha3_serial_fpga_cw310.bin, cw/cw305/simple_capture_traces.py, cw/cw305/simple_capture_traces_batch.py, cw/cw305/util/device.py, python-requirements.txt
This PR adds initial support for capturing sha3/kmac traces and adds `capture aes,` `capture sha3`, `init`, and `plot` commands to the CLI using the `typer` library. This change also refactors device initialization a bit by moving fpga and programmer selection to `device.py` and adds CW310 binaries from lowRISC/opentitan@b1188ef.
This PR includes the following commits:
* Move fpga and programmer selection to device.py
* Add CW310 bitstream and binaries from lowRISC/opentitan@b1188ef
* Use separate config files for aes and sha3 (please don't forget to use `--cfg-file capture_sha3.yaml` for sha3)
* Move output_len to OpenTitan() init
* Add SHA3/KMAC capture support using Typer
I verified that aes capture works on both boards and sha3 capture works on CW310 but I would appreciate it if you …
=> Add SHA3/KMAC capture support using Typer

cw/cw305/capture_aes.yaml, cw/cw305/capture_sha3.yaml, cw/cw305/objs/aes_serial_fpga_cw310.bin, cw/cw305/objs/lowrisc_systems_chip_earlgrey_cw310_0.1.bit, cw/cw305/objs/sha3_serial_fpga_cw310.bin, cw/cw305/simple_capture_traces.py
This PR contains the following improvements to the SHA3 capture:
- Adjust the scope gain
- Verify SHA3 operation using pyXKCP on the host
- Update CW310 binaries for optimized SHA3 captures (less noise, less samples etc.)
I will rebase this once the corresponding OpenTitan PR lowRISC/OpenTitan#8240 has been merged.
=> SHA3 capture improvements

.gitattributes, cw/cw305/objs/aes_serial_fpga_cw310.bin, cw/cw305/objs/aes_serial_fpga_nexysvideo.bin, cw/cw305/objs/lowrisc_systems_chip_earlgrey_cw310_0.1.bit, cw/cw305/objs/lowrisc_systems_chip_englishbreakfast_cw305_0.1.bit, cw/cw305/objs/lowrisc_systems_top_englishbreakfast_cw305_0.1.bit, cw/cw305/objs/sha3_serial_fpga_cw310.bin, cw/cw305/vendor/lowrisc_opentitan.lock.hjson, cw/cw305/vendor/lowrisc_opentitan/cw_spiflash.py
This PR updates all binaries to a more recent version of the OpenTitan repository. All binaries are taken from lowRISC/OpenTitan@862155839 except for the CW305 bitstream for which also lowRISC/OpenTitan@b8f24c491 has been cherry picked to reduce the FPGA resource utilization.
The reason for doing this is that there have been major updates to the hardware IPs and the software, as well as SPI that are incompatible with the previous binaries included in this repo. This complicates experiments with newer bitstreams or modified application binaries.
Signed-off-by: Pirmin Vogel <vogelpi@lowrisc.org>
Update lowrisc_opentitan to lowRISC/opentitan@369cffc85
Update code from upstream repository https://github.com/lowRISC/opentitan to revision 
369cffc85db0e6d5a667676a6f89987b94210e70
* [util,sw] …
=> Update binaries to lowRISC/OpenTitan@862155839

doc/getting_started.md, python-requirements.txt
This PR:
- Clarifies that Python 3.7 or later should be used.
- Fixes a typo in the doc.
- Fixes the ChipWhisperer version to something known good and installs the archive rather than using git checkout in editable mode (may lead to issues with the main OpenTitan install where we can't upgrade the ChipWhisperer toolchain anymore due to the Python 3.6.5 requirement of OT).
=> Documentation and dependency fixes

cw/cw305/capture_aes.yaml, cw/cw305/capture_sha3.yaml, cw/cw305/cw_segmented.py, cw/cw305/simple_capture_traces.py, cw/cw305/simple_capture_traces_batch.py, cw/cw305/util/device.py, python-requirements.txt
This PR contains three commits to optimize the trace capture using ChipWhisperer:
1. The sampling rate is increased to 200 MS/s which is the maximum supported by Husky. CW-Lite keeps collecting traces with 100 MS/s (max supported 105 MS/s) the number of samples to record is adjusted internally for CW-Lite.
2. Allow negative and positive sampling offsets to be defined through the config file. Is allows to better tune the capture window.
3. Tune the capture window for SHA3.
Also, this PR updates the ChipWhisperer version to get a more recent of the library.
=> Optimize SCA trace capture

cw/cw305/simple_capture_traces.py, doc/getting_started.md
The data collection method is based on the derived test requirements
(DTR) for TVLA: https://www.rambus.com/wp-content/uploads/2015/08/TVLA-
DTR-with-AES.pdf section 5.3. Two datasets: fixed key and varying key.
Text is always varying for both datasets. Code snippet tested on CW Husky
Board and CW310 target.
=> [sca] Add AES General Test: FvsR Key.

.gitignore, doc/getting_started.md, python-requirements.txt
The officially recommended way of using ChipWhisperer is to install it in editable mode. We haven't done that so far because for OpenTitan a different version is installed (due to Python 3.6) and in non-editable mode (to speed up CI).
To again use ChipWhisperer in editable mode for ot-sca as recommended and to avoid issues due to having different versions installed in non-editable and editable mode, this commit now switches to a virtual Python environment for ot-sca.
=> Switch to virtual Python env and install ChipWhisperer in editable mode

cw/cw305/capture_aes.yaml, cw/cw305/capture_sha3.yaml, cw/cw305/cw_segmented.py, cw/cw305/simple_capture_traces.py, cw/cw305/simple_capture_traces_batch.py, cw/cw305/util/device.py, python-requirements.txt
This reduced the memory footprint by 4x and will help us to capture more traces without immediately switching to a custom trace format and management. For this to work, some small changes in the ChipWhisperer API are required, see NewAETech/ChipWhisperer#401.
=> Use uint16 instead of double for storing the captured waves

.github/workflows/lintpy.yml
Without the `pull_request` event, the workflow would only trigger on
pushes to branches in the repository.  When pushing to a forked branch,
the workflow would not trigger.  Thus, the `pull_request` event is
required to trigger the workflow in PRs.  The `push` event restricted to
the `master` branch additionally covers pushes directly to the master
branch, without creating a duplicate check on pushes to pull request
branches.
=> Trigger lintpy workflow on pull requests

.gitattributes, .github/workflows/pytest.yml, test/data/tvla_general/sha3_hist_leaking.npz, test/data/tvla_general/sha3_hist_nonleaking.npz, test/repo.py, test/tvla_test.py
This tests the functionality implemented in #89.
=> TVLA: Test histogram loading for general tests

test/data/tvla_general/sha3_hist_leaking.npz, test/data/tvla_general/sha3_hist_nonleaking.npz
This commit compresses the existing test data for the general TVLA test
with `np.savez_compressed()`.  No changes are required to the code, which
can continue to load the data with a simple `np.load()`.  The total file
size of the existing tests is reduced from >150 MiB to <1 MiB.  The
execution time of the tests does not increase measurably.
Part of #96.
=> Compress TVLA general test data

cw/capture.py, cw/capture_sha3_cw310.yaml, cw/objs/sha3_serial_fpga_cw310.bin
KMAC key shares are masked in SW using a 32-bit LFSR.
This commit enables user to specify the LFSR seed in the
configuration file. This feature is needed because unmasked
implementations don't support SW key masking. By re-seeding
LFSR to 0, SW key-masking can be effectively switched off.
Signed-off-by: Vladimir Rozic <vrozic@lowrisc.org>
=> Add support for KMAC SW key masking

cw/tvla.py, cw/tvla_cfg_template.yaml, test/tvla_test.py
Default configurations are specified in yaml file and
it is possible to overwrite them over command line interface.
This is provided by typer library. It also provides descriptions
when typed --help. Updated configurations are written into
a .yaml file after analysis.
=> Add typer CLI and yaml file support to tvla script.

cw/util/device.py
The scope uses the clock provided from the target and depending on the target, it may take some more time for the ADC to actually lock on the clock. With this commit, we wait for up to 1.5s for the ADC to lock instead of just aborting the capture if the ADC hasn't locked yet when first checked.
=> [util/device.py] Wait for ADC lock instead of aborting after first trial

.dockerignore, doc/getting_started.md, util/docker/Dockerfile, util/docker/build_image.sh, util/docker/docker_entrypoint.sh, util/docker/run_container.sh
This PR contains two commits to update the Dockerfile and switch from docker to podman which doesn't require root permissions on the host. This is what we use on our workstation and we might do the same switch also for OpenTitan at some point. At the moment, the generated image is still compatible with docker.
=> [docker/podman] Rework container, switch to podman

cw/objs/lowrisc_systems_chip_earlgrey_cw310_0.1_kmac_dom.bit, cw/objs/sha3_serial_fpga_cw310.bin
Update KMAC bitstream to https://github.com/lowRISC/opentitan/commit/a029fa5c6
The previous version of the bitstream doesn't work with newly generated
binaries.
This bitstream was generated from a recent OpenTitan commit with several
changes applied on top:
KMAC masking enabled
AES masking switched off
OTBN stubbed
Scrambling disabled in flash_ctrl
Signed-off-by: Vladimir Rozic <vrozic@lowrisc.org>
=> [kmac] Update bitstream and binary

.github/workflows/lintpy.yml, .github/workflows/pytest.yml, doc/getting_started.md, util/docker/Dockerfile
Starting with setuptools version 66.0.0, legacy package version names such as 1.1build1 are no longer supported. Since some of our Python dependencies use this format, we pin the setuptools version to the last version before this change. This unblocks CI and gives us time to upgrade/rebase our dependencies.
=> [python-requirements] Pin setuptools version to < 66.0.0

doc/getting_started.md, doc/img/sample_traces_sha3.png
This fixes https://github.com/lowRISC/ot-sca/issues/112
Would be good if s.o. could double check that the png is added correctly to lfs
=> [doc/sha3] add sha3 section to getting-started guide

cw/tvla.py
Please see commit messages for details.
=> [tvla] Fix trace_start argument handling, auto-determine x-label res for t-test step figure

cw/objs/ecc256_keygen_serial_fpga_cw310.bin, cw/objs/lowrisc_systems_chip_earlgrey_cw310_0.1_ecdsa.bit
Adds bitstream with switched off OTBN URND
Bitstream taken from lowrisc master after commit:
https://github.com/lowRISC/opentitan/commit/3f64068d649cf21581f53b241ae7fbfb153c335d 
Corresponding PRs are:
https://github.com/lowRISC/opentitan/pull/17195
and
https://github.com/lowRISC/opentitan/pull/17223
Adds ecc256 keygen serial device binary
Binary compiled from:
https://github.com/jadephilipoom/opentitan/commit/b5a29028c0727452bb207dbbdef66741fb3fce20
Required for https://github.com/lowRISC/ot-sca/pull/115
=> [otbn/tvla] Add bitstream + device binary for OTBN vertical TVLA

cw/capture.py, cw/capture_otbn_vertical.yaml, cw/tvla.py, cw/tvla_cfg_otbn.yaml, cw/util/device.py
This is a PR to bring together the works of Jade, Bilgiday and me
Co-authored-by: Jade Philipoom <jadep@google.com>
Signed-off-by: Michael Tempelmeier <michael.tempelmeier@gi-de.com>
Things to do:
- <del>[ ] Restructure code to support different code snippets</del>
- <del>[ ] add select function to simple serial (python + c)</del>
- <del>[ ] put "golden model" in a function to support different calculations</del>
=> [OTBN] vertical attack initial work

cw/capture.py, cw/tvla.py, cw/util/plot.py
These functions are particularly useful when debugging e.g. cases where the t-test results are not centered around 0.
Below figures show some example plots for SHA3 where I used this to debug a "fake" leakage issue.
1. The average fixed and random trace. They cannot really be distinguished here.
2. The difference between the fixed and random trace average. We see a big peak at the very beginning where the plaintext is loaded. Then the difference slowly and almost linearly decreases while the target is completely idle. This is when the power rails recharge from the initial plaintext loading.
3. The variance for the fixed and random trace set.
4. The difference between the fixed and random trace variance.
5. The resulting TVLA plot. We can see the resulting fake leakage during the idle …
=> [tvla] Add function for plotting average and variance traces and diffs

cw/util/device.py
At the moment the "Connecting and loading FPGA..." is only printed after the FPGA is actually programmed.
This is kind of annoying, because programming the FPGA takes some time and nothing is printed during that time.
As this is the very first message to be printed, it is not obvious what's going on and if the python script is running as expected.
=> Enhance status print while programming the FPGA

cw/tvla.py, cw/tvla_cfg_otbn.yaml, cw/tvla_cfg_template.yaml
This option is currently only available for traces with `dtype=np.uint16`
Do we still support traces with `dtype=np.double`?
It is only tested for otbn and rises a runtime error if used for other modes.
See also: https://github.com/lowRISC/ot-sca/issues/72
=> [otbn/tvla] add option to configure the used samples per trace

cw/capture.py, cw/capture_otbn_vertical.yaml, cw/tvla_cfg_otbn.yaml
This commit adds 
- A batch mode capture function for OTBN vertical ecc256 keygen analysis.
- Additional capture and tvla config files suitable to run with the batch mode (configuration parameters have to be different to the non-batch mode).
The batch mode increases the capture rate, compared to non-batch mode, by approx. 2000% (at least on my FPGA setup). (Before: ca. 20 Traces/s, Now: ca. 400 Traces/s)
First TVLA results look good: (first plot: masks off, 10k traces, second plot: masks on, 40k traces)
Once the corresponding PR for the serial device code (https://github.com/lowRISC/opentitan/pull/17416) is merged I'll open another PR for the built binary.
=> [otbn/tvla] Add batch mode for OTBN vertical ecc256 keygen capture

cw/objs/ecc256_keygen_serial_fpga_cw310.bin
Adds ecc256 keygen serial device binary
Binary compiled from lowrisc OT master after commit: https://github.com/lowRISC/opentitan/commit/894278fb9d7cad111ed715856c0c06a565c366b7
=> [otbn/tvla] Add binary for OTBN vertical batch mode

cw/tvla.py
So far, when capturing traces with offset, the offset isn't taken into account when generating the TVLA plots. This means the trigger highlighting doesn't work properly, when an offset is configured.
This commit/PR fixes this.
=> [tvla] Consider offset in trace/tvla plots for trigger highlighting

cw/capture.py, cw/capture_otbn_vertical.yaml
This commit adds the option to capture datasets for fixed vs random key TVLA analysis for ECC256 keygen algorithm on OTBN. This option is hidden behing the test_type parameter. Currently this option is only enabled for normal capture mode in capture_otbn_vertical() function.
=> [otbn/capture] Add fvsr key test for ECC256 keygen

cw/capture.py
This is to have the same input sequence every time running this function with the same batch_prng_seed.
Corresponding PR in Opentitan repo: https://github.com/lowRISC/opentitan/pull/18210
=> [capture] Set PRNG seed prior to setting fixed seed

cw/capture.py
Code-cleanup for capture.py.
Removes variable reset_firmware as discussed in issue #105 
Closes #105
=> [capture] Removes variable reset_firmware

cw/capture.py, cw/objs/lowrisc_systems_chip_earlgrey_cw310_0.1_ecdsa.bit, cw/objs/otbn_vertical_serial_fpga_cw310.bin
This PR has two commits.
The first commit adds the code for batch-capture OTBN-vertical keygen in the KEY mode.
The second commit updates the bitstream and the binary.
The binary is compiled from [OT PR 18027](https://github.com/lowRISC/opentitan/pull/18027)
=> Keygen batch fvsr key

cw/tvla.py
A bug was introduced to tvla in PR #134 when removing references to mode["otbn_modinv"].
It seems that a part of the condition was not deleted in one of the if branches, which results in an error when running tvla for KMAC.
This commit fixes the condition.
=> [tvla] Bug Fix

cw/capture.py, cw/capture_aes_cw305.yaml, cw/capture_aes_cw310.yaml, cw/objs/aes_serial_fpga_cw305.bin, cw/objs/aes_serial_fpga_cw310.bin, cw/objs/aes_serial_fpga_nexysvideo.bin, cw/objs/lowrisc_systems_chip_earlgrey_cw310_0.1.bit, cw/objs/lowrisc_systems_chip_englishbreakfast_cw305_0.1.bit
This requires the AES target binaries to be updated as well. I'll publish a PR for the changes to `aes_serial.c` upstream and then add the updated binaries to this PR as well.
=> [aes] Add separate SW LFSR for key masking

cw/capture_kmac_cw310.yaml, cw/capture_sha3_cw310.yaml, cw/capture_sha3_masks_off_cw310.yaml, cw/objs/kmac_serial_fpga_cw310.bin, cw/objs/lowrisc_systems_chip_earlgrey_cw310_0.1_kmac_dom.bit, cw/objs/sha3_serial_fpga_cw310.bin
To save logic resources and allow enabling KMAC masking, the following hardware changes have been implemented:
- ECC and scrambling have been disabled for flash_ctrl.
- AES masking has been disabled.
- OTBN has been stubbed out.
The bitstream and binaries have been generated from https://github.com/vogelpi/opentitan/tree/ot-sca_2023-07-15_dd8b709_cw310
=> [kmac, sha3] Update bitstream and binaries to lowRISC/OpenTitan@dd8b709

cw/tvla.py, cw/tvla_cfg_aes_specific_byte0_rnd0.yaml, cw/tvla_cfg_kmac.yaml, cw/tvla_cfg_otbn_keygen.yaml, cw/tvla_cfg_otbn_modinv.yaml, cw/tvla_cfg_sha3.yaml, cw/tvla_cfg_sha3_masks_off.yaml, cw/tvla_cfg_template.yaml, test/tvla_test.py
This PR cleans up tvla code:
1. Renames histogram related arguments
2. Fixes typos and code duplication
3. Refactors code related to saving t-test results
=> [tvla] clean up

cw/tvla.py, test/data/tvla_general/ttest-step-golden.npy.npz, test/tvla_test.py
This PR modifies `test_general_nonleaking_project()` to run TVLA with `--number-of-steps 10` and compare the produced result with the checked-in numerical value, rather than just checking for leakage.
Partially addresses #96
=> [ci] Test stepping function of tvla in CI

cw/test_capture.sh
This PR adds a very simple script to test all capture modes currently supported by `capture.py`. What it does is running the capture commands and copy the trace sample figures under `tmp` for visual inspection. This is useful for a couple of things we need to do soon:
1. Updating ChipWhisperer API
2. Adding CI support
3. Refactoring `capture.py`
The script is not beautiful nor smart but it does what it needs. We can improve / rewrite as we do the things above.
=> Add simple test script to test all modes supported by capture.py

cw/tvla.py, util/ttest.py
This PR consists of two commits with minor clean-ups for tvla.py.
1. Moves all functions for computing t-tests into a separate file
2. Makes 'HAMMING_WEIGHT' the default model for AES leakage
=> [tvla] minor clean-up changes 

cw/capture.py
Writing key at the begining of `capture_kmac_random()` is redundant because `cw.capture_trace()` will send the key on every run.
=> [capture] Remove redundant key write

cw/tvla.py
At the moment we are computing AES leakage in a separate function `compute_leakage_aes()`, while leakage for TVLA general test is computed directly in `run_tvla()`.
This PR adds `compute_leakage_general()` function.
This change is necessary to set the stage for future changes - we plan to add more commands that will make calls to `compute_leakage_general()` and `compute_leakage_aes()`.
=> Compute leakage general

cw/test_waverunner.py, cw/waverunner.py
=> Waverunner: Add functions for load/store of setups to local file

ci/azure-pipelines.yml, ci/ci_capture_aes_cw310.yaml, ci/ci_capture_aes_fvsr.sh
Test PR adds the first FPGA test to the CI.
The test runs `aes-fvsr-key-batch` command, collects 1000 measurements on CW310 and publishes the collected traces.
=> [ci] Add test capture

util/docker/Dockerfile
At the moment, the podman image uses Ubuntu 18.04, which is EOL. This PR updates the image to Ubunt 20.04.
=> [docker/podman] Switch to Ubuntu 20.04

cw/tvla.py, test/data/tvla_general/ttest-step-golden-aes.npy.npz
At the moment trace filtering is enabled only for aes-specific tvla. This PR enables it for general analysis as well.
=> [tvla] Enable filtering

cw/simple_capture_aes_sca.py, cw/simple_capture_aes_sca.yaml, cw/waverunner.py
Added WaveRunner support to `simple_capture_aes_sca.py`. Non-batch/sequence/segmented only for now. Both scopes tested.
Small extension in waverunner.py to support single trace capture.
=> [capture] Added WaveRunner support to simple capture script and cfg file

cw/capture.py
As not all config files yet contain the export keyword, this PR adds code that first checks whether this config entry exists.
=> [capture] Fix project export

doc/getting_started.md, util/docker/Dockerfile, util/docker/docker_entrypoint.sh, util/docker/run_container.sh
Before this commit, the container started as root with the following warnings:
```
Creating user 'ot' with UID=0, GID=0. 
groupadd: GID '0' already exists 
useradd: UID 0 is not unique
runuser: user ot does not exist
root@ot-sca:/repo#
```
With podman 4.3, the option --userns=keep-id when running the container forwards the UID & GID.
Hence, no manual permission management is needed anymore.
Now, the user inside the container matches the user starting it.
=> [docker/podman] Fix user permissions

cw/util/device.py, python-requirements.txt
This PR updates the ChipWhisperer Python dependency to the latest available CW version.
For Husky, we need to make sure that the clkgen is locked after setting the clock.
=> [cw] Update CW Python dependency

ci/azure-pipelines.yml
This is necessary to ensure that adding the CW305 will not mess with the existing pipelines that assumes a CW310
=> [WIP][ci] Make sure the current CI requests a CW310

doc/ci.md
This repo's CI has a couple of quirks that I've tried to document here:
1. We're using a self-managed pool of FPGAs containing both a CW305 and CW310. Selecting the correct one requires matching a tag.
2. We don't run CI for pull requests from forks created by users outside of the lowRISC GitHub organisation. These must be manually approved before they run.
Please let me know if anything's unclear, if this should go elsewhere, or if there's something else you would like documenting.
=> [doc] Add documentation for using CI

ci/azure-pipelines.yml, ci/cfg/ci_tvla_cfg_aes_specific_byte0_rnd0.yaml, ci/ci_check_tvla_aes.sh
Add filter_traces to CI job cfg and increase number of trace captures to 5000 to get consistent TVLA results.
=> [ci] Add filter_traces to CI job

ci/cfg/ci_capture_aes_cw310.yaml, ci/cfg/ci_capture_kmac_cw310.yaml, ci/cfg/ci_capture_otbn_vertical_keygen.yaml, ci/cfg/ci_capture_otbn_vertical_modinv.yaml, ci/cfg/ci_capture_sha3_cw310.yaml, cw/capture.py, cw/capture_aes_cw305.yaml, cw/capture_aes_cw310.yaml, cw/capture_ecdsa256_cw310.yaml, cw/capture_ecdsa384_cw310.yaml, cw/capture_kmac_cw310.yaml, cw/capture_otbn_vertical_keygen.yaml, cw/capture_otbn_vertical_modinv.yaml, cw/capture_sha3_cw310.yaml, cw/capture_sha3_masks_off_cw310.yaml, cw/cw_segmented.py, cw/husky_dispatcher.py, cw/simple_capture_aes_sca.py, cw/simple_capture_aes_sca.yaml, cw/util/device.py
Specify offset in target clock cycles, rather than number of samples.
Partially addresses #177 
For the time being, I've added offset adjustment in the scope code (`cw_segmented.py` and `device.py`), because that's where we can read the sampling rate.
Perhaps there is an elegant way to do this computation without touching the scope code, but I don't see it at the moment.
=> [capture] Specify offset in target clk cycles

python-requirements.txt
As mentioned by @alex-dewar, the chipwhisperer repository link will break soon. Hence, this PR updates the python requirement to point to the chipwhisperer-historical repository.
=> [cw] Replace chipwhisperer repo link

capture/capture_aes.py, capture/configs/aes_sca_cw310.yaml, capture/scopes/chipwhisperer/husky.py, capture/scopes/cycle_converter.py, capture/scopes/scope.py, ci/cfg/ci_aes_sca_fvsr_cw310.yaml, ci/cfg/ci_aes_sca_random_cw305.yaml, ci/cfg/ci_aes_sca_random_cw310.yaml
Previously, the conversion from cycles into samples happened in the Husky scope driver. This PR moves this conversion into a library, allowing the user to either specify offset and windowlength in samples or cycles.
In addition, the sampling rate also can be changed in the config file.
In the future, we want to read the sampling rate from the scope.
=> [scope] Autoconvert cycles into samples

capture/lib/helpers.py
Previously, an error was thrown when the project dir (-p argument) was not provided. Now, instead a warning is printed and the dir is created.
=> Create project dir automatically

python-requirements.txt
As discovered by @johannheyszl, some sqlalchemy versions cause issues when fetching data from the DB. This PR pins all Python requirements to a specifc version. The versions are identical to what currently is used in the podman container.
=> Pin Python requirements to version

doc/getting_started.md
As discovered by @vrozic, older Python versions do not support the required packages. Hence, this PR updates the recommended version in the getting started doc to Python 3.10.
=> [doc] Fix Python version

capture/capture_kmac.py, capture/configs/capture_kmac_cw310.yaml, capture/configs/kmac_cw310.yaml, capture/lib/ot_communication.py, util/data_generator.py
This PR addresses https://github.com/lowRISC/ot-sca/issues/217
As this was a major rework, it would be good if s.o. could test if the TVLA still works.
There are three open points:
1.  FIXMEs in the config file: I'm not sure how to translate the cycles vs. samples
2. In the non-bach fvsr-mode, the internal PRNG is used not AES. This is the same behavior as in the old-script. However we should adjust this eventually.
3. The keyword "ciphertext" is used throughout the script. We should change this to mac or tag eventually.
=> [sca, kmac] Add new capture script for KMAC

capture/capture_aes.py, capture/capture_kmac.py, capture/configs/kmac_cw310.yaml, capture/lib/ot_communication.py, ci/azure-pipelines.yml, ci/cfg/ci_kmac_sca_fvsr_cw310_simpleserial.yaml, ci/cfg/ci_kmac_sca_fvsr_cw310_ujson.yaml, ci/cfg/ci_kmac_sca_random_cw310_simpleserial.yaml, ci/cfg/ci_kmac_sca_random_cw310_ujson.yaml, objs/kmac_ujson_fpga_cw310.bin, util/data_generator.py
Similar to #218 , this PR enables uJSON support for capturing KMAC traces. The device command handler code can be found in [#20563](https://github.com/lowRISC/opentitan/pull/20563).
Consists of three commits:
- uJSON implementation. Closes #238
- Adds KMAC to CI. Closes #237 
- Switch byte array to int array in data generator.
=> [capture] Enable uJSON for KMAC

capture/capture_sha3.py, capture/configs/sha3_sca_cw310.yaml, capture/configs/sha3_sca_cw310_masks_off.yaml, capture/lib/ot_communication.py, ci/azure-pipelines.yml, ci/cfg/ci_sha3_sca_fvsr_cw310_simpleserial.yaml, ci/cfg/ci_sha3_sca_fvsr_cw310_ujson.yaml, ci/cfg/ci_sha3_sca_random_cw310_simpleserial.yaml, ci/cfg/ci_sha3_sca_random_cw310_ujson.yaml, objs/sha3_ujson_fpga_cw310.bin, util/data_generator.py
Similar to #218 , this PR enables uJSON support for capturing SHA3
traces. The device command handler code can be found in [#20593](https://github.com/lowRISC/opentitan/pull/20593).
=> [capture] Enable uJSON for SHA3

capture/capture_aes.py, capture/capture_kmac.py, capture/capture_sha3.py, capture/scopes/chipwhisperer/husky.py, fault_injection/fi_ibex.py, fault_injection/project_library/project.py
This PR removes the path manipulations in the capture and FI scripts. However, due to our directory structure, in some scripts `sys.path.append("../../")` is still needed to find the imports.
Closes #255.
=> Fix relative imports

capture/scopes/chipwhisperer/husky.py
As the user can manually define num_segments in the config file, we need to make sure that we can keep num_segments*num_samples in the CW Husky sample memory.
Closes #247.
=> [scope] Check num_segments_max for CW Husky

fault_injection/configs/pen.global_fi.ibex.char.mem_op_loop.yaml, fault_injection/configs/pen.global_fi.ibex.char.reg_op_loop.yaml, fault_injection/configs/pen.global_fi.ibex.char.unrolled_mem_op_loop.yaml, objs/fi_ibex_fpga_cw310.bin, target/communication/fi_ibex_commands.py
Adds command handlers for the following tests used to characterize Ibex:
- ibex.char.mem_op_loop
- ibex.char.reg_op_loop
- ibex.char.unrolled_mem_op_loop
Device code is located in [#20649](https://github.com/lowRISC/opentitan/pull/20649).
=> [fi] Add Ibex FI characterization handlers

ci/cfg/ci_ibex_fi_vcc_dummy.yaml, fault_injection/configs/pen.global_fi.ibex.char.unrolled_reg_op_loop.yaml, fault_injection/fi_gear/dummy/dummy_vcc.py, fault_injection/fi_gear/fi_gear.py, fault_injection/fi_gear/husky/husky_vcc.py, fault_injection/fi_ibex.py
This PR extends the existing FI setup to generate FI parameters deterministically. This is helpful for certain gear where a random parameter generation is not meaningfull (e.g., X/Y table for LFI).
Each FI gear needs to implement the deterministic parameter generation by themselves. This PR extends the Husky VCC glitcher to either randomly or deterministically generate the paramters.
Closes #253.
=> [fi] Deterministic parameter generation

capture/capture_aes.py, capture/capture_kmac.py, capture/capture_sha3.py, fault_injection/fi_ibex.py, python-requirements.txt, util/helpers.py
This PR enables the user to save the bitstream and the used binary into the project database. Moreover, a CRC of the used binary and bistream is calculated and stored into the database.
Closes #214.
=> [db] Store binary blob into database

fault_injection/fi_gear/dummy/README.md, fault_injection/fi_gear/dummy/dummy_clk.py, fault_injection/fi_gear/dummy/dummy_emfi.py, fault_injection/fi_gear/dummy/dummy_lfi.py, fault_injection/fi_gear/dummy/dummy_vcc.py, fault_injection/fi_gear/fi_gear.py
This PR adds dummy drivers for EMFI, LFI, and CLK glitching FI gear that can be used by others as a template for new FI gear.
Closes #250
Closes #251
Closes #252
=> [fi] Add templates for EM/LFI & clk glitching

capture/capture_otbn.py, capture/configs/otbn_vertical_keygen_sca_cw310.yaml, capture/configs/otbn_vertical_modinv_sca_cw310.yaml, capture/lib/ot_communication.py, objs/otbn_vertical_serial_fpga_cw310.bin
This PR
- addresses issue https://github.com/lowRISC/ot-sca/issues/216
- adds a capture script for OTBN vertical analysis, which supports "keygen" and "modinv" OTBN apps.
-> For this, capture_aes.py is used as a template.
- updates the OTBN vertical device binary.
=> [capture] Add capture script for OTBN vertical analysis

analysis/configs/tvla_cfg_aes_specific_byte0_rnd0.yaml, analysis/configs/tvla_cfg_kmac.yaml, analysis/configs/tvla_cfg_otbn_keygen.yaml, analysis/configs/tvla_cfg_otbn_modinv.yaml, analysis/configs/tvla_cfg_sha3.yaml, analysis/tvla.py, capture/capture_aes.py, capture/capture_kmac.py, capture/capture_otbn.py, capture/capture_sha3.py, capture/configs/otbn_vertical_keygen_sca_cw310.yaml, capture/configs/otbn_vertical_modinv_sca_cw310.yaml
This commit fixes incompatibility of tvla plotting with the new database and metadata format.
For this, additional metadata is stored in aes, otbn, kmac and sha3 capture. Also, a new wrapper function for plotting is added to the tvla script. Finally, aes, otbn, kmac and sha3 config files are adjusted.
Further, this PR adds code to also include metadata in plots of aes specific tests.
Through this PR two tasks in https://github.com/lowRISC/ot-sca/issues/72 are addressed:
=> [tvla] Fix plotting issues with new database and metadata format

capture/capture_aes.py, capture/capture_kmac.py, capture/capture_otbn.py, capture/capture_sha3.py, capture/project_library/project.py
When using the CW trace database format, we disable all but the last two trace storage segments during captures to maintain high capture rates. Before storing the database to disk at the end of the capture, all trace storage segments need to be re-enabled. Otherwise, only 20k traces are read from the database upon loading.
This resolves lowRISC/ot-sca#274.
=> [capture] Re-enable all CW trace storage segments before saving to disk

analysis/tvla.py
For both these cases we should maybe add a CI check.
=> [tvla] Fix plotting of results for byte-specific AES, as well as when using the legacy CW database format

capture/capture_aes.py
Previously, the were mixed up. In addition, the LFSR also needs to be seeded in non-batch mode. Otherwise, the masking cannot be switched on or off.
This resolves lowRISC/ot-sca#279.
=> [capture, aes] Fix usage of batch_prng_seed and lfsr_seed variables

capture/project_library/ot_trace_library/trace_library.py, capture/project_library/project.py
This PR fixes issues that could occur when accessing the DB using multiple processes:
- When opening the DB, check if the DB already exists.
- When closing the DB, properly close the connection to the DB engine.
Moreover, also check if the user accidentally did not provide the DB file path with the .db extension. If this happens, simply add it to the path.
=> [db] Fix DB opening and closing

analysis/configs/tvla_cfg_aes_specific_byte0_rnd0.yaml, analysis/tvla.py, ci/azure-pipelines.yml, ci/cfg/ci_tvla_cfg_aes_specific_byte0_rnd0.yaml, ci/cfg/ci_tvla_cfg_aes_specific_byte_0_15_rnd_0_1.yaml
This PR is related to #287 and contains two commits:
1. Enable passing lists of selected rounds and bytes for the byte-specific AES TLVA
2. Add a new CI job to exactly test this as well as other byte-specific TVLA functions
=> [tvla] Enable passing lists of selected rounds/bytes for byte-specific AES, add new CI job

analysis/tvla.py, capture/project_library/ot_trace_library/trace_library.py, capture/project_library/project.py
Previously, retrieving parts of a dataset (e.g., plaintext, ciphertext, ...) did not work as there was a bug in the array slicing logic.
Basically, if start and end or end was not provided, "None" is the default value. However, the check in the if condition should be `if (start is not None)` and not `if (start)`.
This PR fixes this issue.
Moreover, now it is also possible to select a single entry of a dataset, e.g., `get_plaintexts(0)` returns the plaintext at DB ID 0.
=> [db] Fix bug in array slicing

ci/cfg/ci_kmac_sca_random_cw310_simpleserial.yaml, ci/cfg/ci_kmac_sca_random_cw310_ujson.yaml
This PR reduces the number of traces to be recorded from 1000 to 100 for non-batch tests. For testing whether capture works, this is still enough and it speeds up CI.
=> [ci] Reduce number of traces

capture/configs/aes_sca_cw310.yaml, capture/configs/kmac_sca_cw310.yaml, capture/configs/sha3_sca_cw310.yaml, capture/configs/sha3_sca_cw310_masks_off.yaml, ci/cfg/ci_kmac_sca_fvsr_cw310_simpleserial.yaml, ci/cfg/ci_kmac_sca_fvsr_cw310_ujson.yaml, ci/cfg/ci_kmac_sca_random_cw310_simpleserial.yaml, ci/cfg/ci_kmac_sca_random_cw310_ujson.yaml, ci/cfg/ci_sha3_sca_fvsr_cw310_simpleserial.yaml, ci/cfg/ci_sha3_sca_fvsr_cw310_ujson.yaml, ci/cfg/ci_sha3_sca_random_cw310_simpleserial.yaml, ci/cfg/ci_sha3_sca_random_cw310_ujson.yaml, doc/getting_started.md, objs/aes_ujson_fpga_cw310.bin, objs/kmac_ujson_fpga_cw310.bin, objs/sca_ujson_fpga_cw310.bin, objs/sha3_ujson_fpga_cw310.bin
As the KMAC, SHA3, and AES SCA applications are collected in the same uJSON binary, this PR removes the individual uJSON binaries used so far and replaces them with the combined sca_ujson_fpga_cw310 binary.  In addition, this update is needed as some binaries previously did not had access to the SW trigger, which is needed for tests on discrete. This binary was generated from OpenTitan commit: [b2d9b8356aa72164fb828e60ca8118495df6669d](https://github.com/lowRISC/opentitan/commit/b2d9b8356aa72164fb828e60ca8118495df6669d) with the command:
`bazel build //sw/device/tests/crypto/cryptotest/firmware:firmware`
=> [capture] Update uJSON binaries

analysis/tvla.py
Previously, the TVLA script made assumption on how the project filename is formated, i.e.,
'../capture/projects/simple_capture_aes_sca'. This PR changes the parsing of this filename to also allow other filename formats.
=> [analysis] Fix title parsing in TVLA

target/cw_fpga.py
CW Husky often blocks USB communication after power-up. 
This is causing problems with CI whenever Huskies are power-cycled.
Initializing the scope twice seems to solve the problem.
=> [capture] Unblock Husky USB communication after power-up

target/communication/sca_sha3_commands.py
This PR should fix the 'Acknowledge error: Device and host not in sync' error message that occasionally occured in the CI for SHA3 measurements when using uJSON.
With this change, the _ujson_sha3_sca_ack waits now until the ACK flag is received. If the device is, for some reason, really not responding, the readline() function times out and the exception is raised.
Closes #283
=> [sca] Fix ACK for uJSON SHA3

analysis/configs/tvla_cfg_aes_specific_byte0_rnd0.yaml, analysis/configs/tvla_cfg_kmac.yaml, analysis/configs/tvla_cfg_otbn_keygen.yaml, analysis/configs/tvla_cfg_otbn_modinv.yaml, analysis/configs/tvla_cfg_sha3.yaml, analysis/configs/tvla_cfg_sha3_masks_off.yaml, analysis/configs/tvla_cfg_template.yaml, analysis/tvla.py, ci/cfg/ci_tvla_cfg_aes_specific_byte0_rnd0.yaml, ci/cfg/ci_tvla_cfg_aes_specific_byte_0_15_rnd_0_1.yaml, test/tvla_test.py, util/leakage_models.py
This commit enables TVLA fixed-vs-random data analysis. In addition, this commit re-names related functions and variables to more accurate and intuitive names.
The main change is in `tvla.py`
The remaining changes are mostly in configuration files due to changing parameter from boolean `general_test` to string `test_type` in `"GENERAL_KEY", "GENERAL_DATA", "SPECIFIC"`.
=> [tvla] Enable TVLA general-data analysis

capture/capture_sha3.py, target/chip.py, target/communication/sca_sha3_commands.py
When no response is received from the device, restart it and try again. This is helpful to avoid that a single missed response from the device requires us to throw away the entire capture results.
Currently only implemented for SHA3 to test the code.
=> [capture] Reset device on no response

capture/capture_aes.py, capture/capture_kmac.py, capture/capture_otbn.py, capture/capture_sha3.py, fault_injection/fi_ibex.py
This parameter got somehow dropped and was no longer read from the capture config file. As a result, we were always using the same bitstreams. For example, the SHA3 measurements produce the following CI artifact:
Whereas the correct plot would look like this (generated locally using the "same" bitstream and binary):
The active portion of the trace is 4x longer as the masked SHA3 takes 4 cycles per round vs. 1 cycle for the unmasked implementation.
=> [capture] Re-add force_program_bitstream to target_cfg

capture/scopes/waverunner/waverunner.py
When using the WaveStudio GUI to access the scope, this application reconfigures the format of the command responses to CHDR=OFF, i.e., there is no header. However, the Waverunner driver we are using requires that the commands are acknowledged in the header using CHDR=SHORT.
=> [scope] Set WaveRunner short command header

analysis/tvla.py
This PR optimizes the memory consumption of the TVLA script by freeing some memory objects. By setting an array to None, the Python internal garbage collector takes care of actually freeing the memory. With this PR, I've managed to reduce the mem. consumption of certain parts of the script to -50%.
=> [tvla] Optimize memory usage

analysis/trace_preprocessing.py, capture/project_library/ot_trace_library/trace_library.py, doc/getting_started.md
This PR adds a trace preprocessing script allowing the user to (a) filter traces using a max. amount of tolerable deviation from the trace average and (b) align the traces using a reference window. Currently, the script is tested with the new trace database format. Moreover, I've decided to implement this functionality outside of the TVLA script as this script is already really overblown.
Input trace set:
After filtering:
After aligning:
The aligning (which uses functionality from ChipWhisperer) heavily depends on the selected alignment window.
=> [analysis] Add trace preprocessing

analysis/trace_preprocessing.py, doc/getting_started.md, util/plot.py
With this PR, the reference trace for the trace aligning function is determined by calculating the mean over num_traces_mean traces. The reason for that is that the trace aligning function achieves better results by using the mean as a reference trace.
=> [analysis] Trace aligning using mean trace

capture/capture_aes.py, capture/capture_kmac.py, capture/capture_otbn.py, capture/capture_sha3.py, fault_injection/fi_ibex.py, target/chip.py, target/targets.py
This PR adds support for having multiple chips attached to the computer. By providing the serial number of the chip using the "usb_serial:: entry in the config files, ot-sca is capable of programming the correct device.
=> [chip] Add support for multiple chips

capture/capture_aes.py, objs/sca_ujson_fpga_cw310.bin, target/communication/sca_aes_commands.py
On the FPGA, the AES core automatically raises the SCA trigger we are using for capturing traces. However, on the chip this functionality is disabled.
This PR transmits the fpga_mode bit to the code running on the FPGA or the chip. Based on this bit, the target code either manually raises the trigger or lets the AES core handle automatically the trigger.
The target code is available in https://github.com/lowRISC/opentitan/pull/21741 and the binary
sca_ujson_fpga_cw310 was created using this PR and the command:
./bazelisk.sh build //sw/device/tests/crypto/cryptotest/firmware:firmware
=> [capture] Add FPGA mode for AES

.github/workflows/fpga.yml, doc/ci.md
This PR adds a GitHub Actions workflow which performs the same tasks as the Azure pipeline that runs FPGA jobs.
This work is part of a move from Azure to GitHub Actions generally in OpenTitan.
I'm planning to leave the `ci/azure-pipelines.yml` file here for a short while in case we have any issues with the GitHub Actions workflow so that we can switch back easier. Once we know it's working well we can remove that configuration.
=> Add GitHub Actions FPGA workflow

fault_injection/configs/pen.global_fi.ibex.char.conditional_branch.cw310.yaml, fault_injection/configs/pen.global_fi.ibex.char.flash_read.cw310.yaml, fault_injection/configs/pen.global_fi.ibex.char.flash_write.cw310.yaml, fault_injection/configs/pen.global_fi.ibex.char.sram_read.cw310.yaml, fault_injection/configs/pen.global_fi.ibex.char.sram_write.cw310.yaml, fault_injection/configs/pen.global_fi.ibex.char.unconditional_branch.cw310.yaml, objs/sca_ujson_fpga_cw310.bin, target/communication/fi_ibex_commands.py
This commit adds the command handlers and configs for the following Ibex FI penetration tests:
- ibex.char.flash_read
- ibex.char.flash_write
- ibex.char.sram_read
- ibex.char.sram_write
- ibex.char.unconditional_branch
- ibex.char.conditional_branch
The device code is located in lowRISC/opentitan#22135 and the binary was compiled from this PR using:
./bazelisk.sh build //sw/device/tests/crypto/cryptotest/firmware:firmware_fpga_cw310_test_rom
=> [fi] Command handlers for Ibex tests

util/plot.py
This commit optimizes the generation of the FI scatter plot. Instead of calling plot.scatter() for each datapoint, now, an array is passed to the function. With this changes, scatter plots with >100k points can be plotted, which was not possible before this change.
=> [fi] Optimize plot generation

fault_injection/project_library/ot_fi_library/fi_library.py
Similar to lowRISC/ot-sca#294, this commit fixes the array splicing for the FI database. Now, only the selected DB entries are returned instead all of them.
=> [fi] Fix array splicing in DB

fault_injection/fi_gear/fi_gear.py, fault_injection/fi_gear/husky/husky_vcc.py, util/check_version.py
This commit enables us to run multiple FI setups using different Huskies. For this, the serial number can be specified with the fisetup.fi_gear_sn parameter in the config.
=> [fi] Add support for multiple Huskies

util/db_to_zarr_converter.py
This commit adds a converter tool capable of converting SCAProject libraries (CW or ot_trace_library) into a zarr database. This can be useful when experimenting with other SCA libraries, e.g., [decryptofy/scarr](https://github.com/decryptofy/scarr).
=> [util] Add DB converter tool

analysis/tvla.py
Previously, when number_of_steps > 1, the TVLA plot only contained the number of traces used for a step, but not the total number of traces processed. This PR fixes the issue, now the total number of used traces is printed in the figure.
=> [analysis] Fix num_traces in TVLA plot

fault_injection/configs/pen.global_fi.ibex.char.sram_static.cw310.yaml, target/communication/fi_ibex_commands.py
This commit adds the command handler for the
ibex_char_sram_write test. The device PR is located in lowRISC/opentitan#22272
=> [fi] Add SRAM static cmd handler

.github/workflows/fpga.yml, ci/azure-pipelines.yml, ci/cfg/ci_crypto_aes_vcc_dummy_cw310.yaml, fault_injection/configs/pen.global_fi.crypto.aes.cw310.yaml, fault_injection/configs/pen.global_fi.crypto.kmac.cw310.yaml, fault_injection/fi_crypto.py, target/communication/fi_crypto_commands.py
This commit adds the handlers for the following tests:
- crypto_fi_aes_key
- crypto_fi_aes_plaintext
- crypto_fi_aes_encrypt
- crypto_fi_aes_ciphertext
- crypto_fi_kmac_key
- crypto_fi_kmac_absorb
- crypto_fi_kmac_squeeze
The device PR is located in lowRISC/opentitan#22505
=> [fi] Add AES and KMAC handlers

target/targets.py
This commit fixes the re-init of the COM interface after a reset was issued by the attack script.
=> Re-establish com interface after reset

analysis/tvla.py
Previously, in i_step=0, the TVLA script opened all plaintext or keys at once. This is problematic, as for large datasets and large keys/ptx the memory consumption is tremendous.
This commit optimizes memory utilization by just opening the keys/ptx that correspond to the current step.
=> [tvla] Optimize memory utilization

fault_injection/fi_otbn.py, target/communication/fi_otbn_commands.py
This PR updates the OTBN Key Sideload hander to refect changes in the repo.
=> [fi] Update OTBN Key Sideload handler

fault_injection/configs/pen.global_fi.ibex.char.hardened_check_eq_unimps.cw310.yaml, target/communication/fi_ibex_commands.py
This commit adds the following FI test command handlers:
- ibex_char_hardened_check_eq_unimp
- ibex_char_hardened_check_eq_2_unimps
- ibex_char_hardened_check_eq_3_unimps
=> [fi] Add additional hardened check cmd handlers

fault_injection/configs/pen.global_fi.rng.csrng.cw310.yaml, fault_injection/configs/pen.global_fi.rng.edn.cw310.yaml, fault_injection/fi_rng.py, target/communication/fi_rng_commands.py
This commit adds the command handler for the RNG FI tests. Currently the csrng test is supported.
=> [fi] Add RNG command handler

fault_injection/configs/pen.global_fi.otbn.char.bn.rshi.cw310.yaml, fault_injection/configs/pen.global_fi.otbn.char.bn.sel.cw310.yaml, fault_injection/configs/pen.global_fi.otbn.char.mem.cw310.yaml, fault_injection/configs/pen.global_fi.otbn.pc.cw310.yaml, fault_injection/fi_otbn.py, target/communication/fi_otbn_commands.py
This PR consists of the following two commits:
- Extend the OTBN FI script such that inputs or initial configs can be transmitted
- Add new OTBN FI test command handlers
=> [fi] Add new OTBN tests and enable transmitting payload

capture/capture_aes.py, capture/capture_hmac.py, capture/capture_ibex.py, capture/capture_kmac.py, capture/capture_otbn.py, capture/capture_sha3.py, fault_injection/fi_crypto.py, fault_injection/fi_ibex.py, fault_injection/fi_otbn.py, fault_injection/fi_rng.py, target/chip.py, target/targets.py
The voyager board uses the "ftdi" interface while other boards use the "hyper310" interface. This commit makes the interface parameterisable. By setting
```
target:
interface: "ftdi"
```
in the corresponding FI/SCA config, ot-sca can be used to analyze
the voyager board.
=> [chip] Add interface option

.github/workflows/lintpy.yml, .github/workflows/pytest.yml
Recently, the pytest and lintpy jobs were failing. The reason for this is that we are running these jobs on the latest Ubuntu version. However, we currently recommend using Ubuntu 22.04. Hence, lets pick this runner for the CI jobs.
Closes lowRISC/ot-sca#388
=> [ci] Fix CI runners

capture/capture_aes.py, capture/capture_hmac.py, capture/capture_ibex.py, capture/capture_kmac.py, capture/capture_otbn.py, capture/capture_sha3.py, capture/scopes/chipwhisperer/husky.py, capture/scopes/scope.py, fault_injection/fi_crypto.py, fault_injection/fi_ibex.py, fault_injection/fi_otbn.py, fault_injection/fi_rng.py, target/cw_fpga.py, target/targets.py, util/spiflash.py
Previously, attaching only one CW310 and Husky when not using a container was possible. With this commit, multiple boards and scopes can be connected when providing the ID of the Husky/CW FPGA board.
=> [cw] Add ID to CW Husky and CW310

fault_injection/configs/pen.global_fi.otp_ctrl.data_read.cw310.yaml, fault_injection/fi_otp.py, target/communication/fi_otp_commands.py
This PR adds code for FI pen-testing the OTP module.
The test sequence can be summarized in the following way:
1. Read content from a selected OTP partition for comparison values
2. Perform fault injection on nop instructions
3. Read content from the same OTP partition again
4. Compare output with previous output and check if values differ
The OTP partition to read can be selected through the "which_test" parameter in the config file.
The corresponding PR in lowRISC/opentitan is https://github.com/lowRISC/opentitan/pull/23156
=> [fi/otp] Add OTP data read test to FI framework

capture/capture_otbn.py, target/communication/sca_otbn_commands.py
This commit adds the following OTBN SCA routines to the code base:
- init: Init the OTBN SCA test on the device
- init_keymgr: Prepare the keymanager for the OTBN key sideloading test
- key_sideload_fvsr: Start the test
- read_response: Read response from device
- ecdsa_p256_sign: Test available in single, batch, and FvsR mode
Please note that this commit only adds these tests to the communication
stack but not to the capture script.
=> [sca] Add KeySideloadFvsr and EcdsaP256 OTBN tests

fault_injection/configs/pen.global_fi.crypto.sha256.cw310.yaml, target/communication/fi_crypto_commands.py
This commit adds the command handlers for the Sha256 FI tests to ot-sca.
=> [fi] Add Sha256 command handlers
