README.md
Signed-off-by: Alphan Ulusoy alphan@google.com
=> Add some references to readme.md

cw/cw305/capture.yaml, cw/cw305/capture_traces.py, cw/cw305/mix_columns_capture.py, cw/cw305/mix_columns_cpa_attack.py, cw/cw305/util/device.py, cw/cw305/util/plot.py, python-requirements.txt
Add mix_column HD attack. The attack leverages the mix column attack model implemented in the ChipWhisperer library. See Python module documentation for more details.
=> Mix columns attack

cw/cw305/correlation-enhanced_collision_attack.py
This is related to #11 supersedes #18 (I couldn't push anymore to the other PR).
It contains the same content + a requested comment. Sorry @alphan , could you please again approve this?
=> Add correlation-enhanced collision attack

cw/cw305/util/plot.py
This change adds crosshair and hover tools to bokeh html output:
=> Add crosshair and hover tools to bokeh html output

cw/cw305/simple_capture_traces.py
Signed-off-by: vrozic <vrozic@lowrisc.org>
=> [sca] Capture setup for general fixed-vs-random TVLA

cw/cw305/capture.py
=> Add lines to set key and text len in AES mix column capture.

cw/cw305/capture.py
In order to simplify the analysis, the first encryption has to use
fixed key. In addition a PRNG is used for random key and plaintext
generation instead of AES algorithm as specified in the TVLA DTR.
aes_serial firmware is also updated to support this functionality.
=> Add support for AES TVLA fixed-vs-random key captures in batch mode.

doc/getting_started.md
Update binaries for AES FvsR key batch capture. Update getting
started guide especially with bazel commands.
=> Update binaries and getting started guide.

cw/cw305/capture.py, cw/cw305/objs/sha3_serial_fpga_cw310.bin
Added support for batch capture for fixed-vs-random general TVLA.
Signed-off-by: vrozic <vrozic@lowrisc.org>
=> [sca] Batch capture support for KMAC.

cw/cw305/tvla.py
Signed-off-by: Vladimir Rozic <vrozic@lowrisc.org>
=> [tvla] Enable histogram loading for general tests.

cw/capture.py, cw/capture_sha3_cw310.yaml, python-requirements.txt
Please see commit description.
=> Add missing check_range() calls, fix bokeh dependency used for plotting captured traces

cw/capture.py
`pll_frequency` is in Hz not in MHz
=> [sca] fix magnitude of frequency in print function

cw/capture.py
In case a huge number of traces is captured, this handler allows the
user, when capturing takes too much time, to abort the capture without
losing previously recorded data.
To use this handler it has to be registered within each of the capture
functions, where a Chipwhisperer project is used to store traces.
=> [sca/capture] Add Ctrl-C handler to capture script

cw/tvla.py
This PR contains three small fixes for TVLA. For details refer to the commit messages.
=> [tvla] Various small fixes

cw/capture.py, cw/tvla.py
This commit adds code, which saves metadata from trace capturing to the CW project file. This data then can be used in the TVLA script without having to hand over the corresponding capture configuration file. Here, this commit adds code to display metadata in the TVLA plot.
In general this makes capture projects as well as TVLA plots more distinguishable, and prevents getting confused with configuration parameters.
For now this is only implemented for OTBN vertical TVLA, but it shouldn't be too much work to add to the other capture modes. A TVLA plot using these modifications looks like this:
I'll open this as a draft pull request, as this was just some work I did on the side, while working on OTBN vertical capture/TVLA.
We should discuss if we want/need something like this or not, and in …
=> [tvla] Save capture metadata to CW project file + use it in TVLA plot

cw/capture.py, cw/capture_aes_cw305.yaml, cw/capture_aes_cw310.yaml, cw/capture_ecdsa384_cw310.yaml, cw/capture_ecdsa_cw310.yaml, cw/capture_kmac_cw310.yaml, cw/capture_otbn_vertical.yaml, cw/capture_sha3_cw310.yaml, cw/capture_sha3_masks_off_cw310.yaml, cw/util/device.py
This feature is especially necessary when accessing FPGAs connected to remote server and one cannot power-off and on the FPGA board to trigger bitstream programming.
=> [capture] Add force programming of FPGA over CLI

cw/capture.py, cw/capture_sha3_cw310.yaml
This PR contains two commits for the SHA3 capture. The second one is very relevant, I think this might potentially resolve also the issue @y-srini has been facing. I've found this out using the plots added with PR #121 .
=> [capture] Fixes for SHA3 capture

cw/capture.py, cw/cw_segmented.py
This commit replaces the hardcoded value of 100000000 for pll_frequency in cw_segmented with a value loaded from the config file.
This change closes #129
=> [capture] Replacing hardcoded value with pll_frequency

cw/tvla.py, cw/tvla_cfg_aes_specific_byte0_rnd0.yaml
This PR makes two changes:
1. adds configuration file for running TVLA on AES
2. Modifies figure layout of AES TVLA specific test results to be consistent with other figures.
=> [tvla] AES configuration file and figure layout improvements

doc/getting_started.md
This PR streamlines the getting started document:
- Move hardware setup to the Prerequisites section. Previously, when following the tutorial step by step, the hardware setup was introduced after the first capturing of traces.
- Merge redundant UDEV Rules section and move to the Prerequisites section.
- Fix dead link to ChipWhisperer dependencies.
=> [doc] Streamline getting_started

doc/getting_started.md
This PR adds instructions on how to revive CW-Husky when it is not reachable anymore after, e.g., a FW update.
=> [doc] Add reviving Husky instructions

.github/CODEOWNERS
Updates the list of codeowners (default reviewers)
=> Updates Codeowners

util/docker/Dockerfile
This PR updates the container to Ubuntu 22.04.
=> [podman] Update to Ubuntu 22.04

cw/simple_capture_aes_sca.py, cw/util/plot.py
After recording traces we can inspect them using the plot function. It is often helpful to see a mean trace along with +/- stdev to judge capture quality. 
Example after zooming in a bit:
(Also includes a small bugfix in capture script)
=> Add parameter to plot function to display mean and stdevs

cw/tvla.py
Before starting the analysis, tvla filters out the noisy traces.
This PR makes trace-filtering optional via input argument. The default value is True.
=> [tvla] Make trace filtering optional.

ci/azure-pipelines.yml, ci/cfg/ci_capture_kmac_cw310.yaml, ci/cfg/ci_capture_otbn_vertical_keygen.yaml, ci/cfg/ci_capture_otbn_vertical_modinv.yaml, ci/cfg/ci_capture_sha3_cw310.yaml, ci/ci_capture_all.sh
extend CI with AES, KMAC, SHA3 and OTBN capture tests
=> [ci] experiment

ci/azure-pipelines.yml, ci/cfg/ci_capture_ecdsa256_cw310.yaml, ci/cfg/ci_capture_ecdsa384_cw310.yaml, ci/ci_capture_all.sh
Adds measurements of ECDSA-256 and ECDSA-384 to the CI. Tests both simple and stream mode.
=> [ci] Add OTBN horizontal measurements to CI

capture/README.md, capture/capture_aes.py, capture/scopes/chipwhisperer/husky.py, util/check_version.py, util/update_husky_fw.py
As this repository requires a specific ChipWhisperer API version as well as ChipWhisperer Husky firmware version, this PR adds a version check to both.
=> Add CW version check

capture/capture_aes.py
At the moment AES fixed-vs-random non-batch capture doesn't work properly.
The problem is that the cipertext variable is updated too soon, so the received ciphertext is compared with the result of the following encryption, causing `Uncorrect encryption result` error.
This PR fixes it.
The patch is not the most elegant, but things will simplify later on when I modify `data_generator.py` to include random capture.
Thanks @m-temp for pointing out this problem
=> [capture] Fixes AES fixed-vs-random non-batch capture

doc/getting_started.md, doc/img/aes_traces.jpg
This PR updates some outdated instructions in the getting started guide.
=> [doc] Updating AES capture documentation

capture/capture_aes.py, capture/capture_kmac.py, capture/capture_sha3.py, fault_injection/fi_ibex.py, util/helpers.py
This PR allows the user to pass notes as an argument to the project database.
Closes #213.
=> [db] Add notes to database

target/cw_fpga.py
Previously, we re-programmed the FPGA when a FI crashed OpenTitan running on CW310. As this took quite some time, we now read the INITB pin - this pin returns false or none when the FPGA is not programmed or the bitstream CRC does not match.
In this case, we are re-programming the bistream.
When the bitstream is OK, we simply reset OpenTitan by using the power on reset pin (POR_N is mapped to USB_A14 on CW310).
This significantly increases the FI rate.
Closes #249.
=> [fi] Reset OpenTitan on faulty behavior

capture/lib/ot_communication.py, objs/sha3_ujson_fpga_cw310.bin
Changes SHA to SHA3 naming convention.
=> [capture] Change SHA to SHA3

capture/capture_aes.py, capture/capture_kmac.py, capture/capture_otbn.py, capture/capture_sha3.py, capture/scopes/chipwhisperer/husky.py, capture/scopes/scope.py
If no num_segments is provided in the config file for Husky, the scope driver automatically sets it to num_segments_max.
For WaveRunner, an error is raised if no num_segments max is provided.
Closes #277.
=> [capture] Set num_segments to max

capture/project_library/ot_trace_library/trace_library.py
This PR fixes a bug when reading keys from the database. Thanks @vrozic for finding this!
=> [db] Fix database reading

.gitattributes, capture/capture_aes.py, capture/capture_kmac.py, capture/capture_otbn.py, capture/capture_sha3.py, capture/configs/aes_sca_chip.yaml, capture/configs/sha3_sca_chip_masks_off.yaml, fault_injection/fi_ibex.py, target/chip.py, target/lib/opentitantool, target/targets.py
This PR adds support for flashing, resetting, and communicating with the discrete OpenTitan chip.
=> Add support for the OpenTitan chip

capture/configs/kmac_sca_cw310_chip.yaml, capture/configs/sha3_sca_chip_masks_off.yaml
This PR adds a capture script for KMAC and adapts the WaveRunner IP.
=> [capture] Add capture scripts

util/data_generator.py
This PR fixes a bug in the SHA3 data generator that returned a non-fixed message for the SHA3 FVSR non-batch mode.
=> [capture] Fix SHA3 FVSR

capture/capture_aes.py, capture/capture_kmac.py, capture/capture_otbn.py, capture/capture_sha3.py, capture/scopes/scope.py, capture/scopes/waverunner/waverunner.py
This PR enables to select the resolution of the attached LeCroy oscilloscope, i.e., 8-, 12-, or 16-bit.
=> [capture] Implement 12- and 16-bit LeCroy support

analysis/configs/tvla_cfg_aes_specific_byte0_rnd0.yaml, analysis/tvla.py, ci/cfg/ci_tvla_cfg_aes_specific_byte0_rnd0.yaml, ci/cfg/ci_tvla_cfg_aes_specific_byte_0_15_rnd_0_1.yaml, test/tvla_test.py, util/histograms.py, util/leakage_models.py
This PR adds AES specific bit-based analysis to TVLA.
For easy review, this PR is divided into 9 commits, some of which will be squashed before merging (indicated in commit messages)
=> Add bit-based AES leakage model

ci/azure-pipelines.yml, ci/cfg/ci_otbn_fi_vcc_dummy_cw310.yaml, fault_injection/configs/pen.global_fi.ibex.char.reg_op_loop.cw310.yaml, fault_injection/configs/pen.global_fi.ibex.char.unrolled_mem_op_loop.cw310.yaml, fault_injection/configs/pen.global_fi.ibex.char.unrolled_reg_op_loop.cw310.yaml, fault_injection/configs/pen.global_fi.otbn.char.hardware_dmem_op_loop.cw310.yaml, fault_injection/configs/pen.global_fi.otbn.char.hardware_reg_op_loop.cw310.yaml, fault_injection/configs/pen.global_fi.otbn.char.unrolled_dmem_op_loop.cw310.yaml, fault_injection/configs/pen.global_fi.otbn.char.unrolled_reg_op_loop.cw310.yaml, fault_injection/fi_otbn.py, objs/fi_ibex_fpga_cw310.bin, objs/sca_ujson_fpga_cw310.bin, target/communication/fi_otbn_commands.py
This PR adds the scripts for performing fault injection attacks on OTBN.
The binary was created from lowRISC/opentitan#21642
=> [fi] Add OTBN scripts

fault_injection/fi_ibex.py, fault_injection/fi_otbn.py
This commit adds an evaluation log, i.e., the total number of faults, the number of expected results, no responses, and unexpected results.
=> [fi] Add evaluation log

fault_injection/configs/pen.global_fi.ibex.char.register_file.cw310.yaml, fault_injection/configs/pen.global_fi.ibex.char.register_file_read.cw310.yaml, target/communication/fi_ibex_commands.py
This commit adds the command handlers for the following FI tests:
- ibex.char.register_file_read
- ibex.char.register_file
The device code is located in lowRISC/opentitan#21359
=> [fi] Add register file cmd handler

fault_injection/fi_gear/chipshouter/chipshouter.py, fault_injection/fi_gear/fi_gear.py, python-requirements.txt
This commit adds support for doing EMFI with the ChipShouter and the ChipShover XZY table.
=> [fi] Add ChipShouter and ChipShover support

analysis/trace_preprocessing.py, doc/getting_started.md
This commit adds the possibility of using multiple jobs for aligning the traces.
=> [analysis] Add multi-processing for trace aligning

capture/capture_ibex.py, capture/configs/ibex_sca_chip.yaml, capture/configs/ibex_sca_cw310.yaml, ci/cfg/ci_ibex_sca_cw310_ujson.yaml, objs/sca_ujson_fpga_cw310.bin, target/communication/sca_ibex_commands.py
This commit adds the command handler for:
- ibex_sca_tl_write_batch_fvsr
- ibex_sca_tl_write_batch_fvsr_fix_address
- ibex_sca_tl_write_batch_random
- ibex_sca_tl_write_batch_random_fix_address
- ibex_sca_tl_write_fvsr
- ibex_sca_tl_write_random
- ibex_sca_tl_read_batch_fvsr
- ibex_sca_tl_read_batch_fvsr_fix_address
- ibex_sca_tl_read_batch_random
- ibex_sca_tl_read_batch_random_fix_address
- ibex_sca_tl_read_fvsr
- ibex_sca_tl_read_random
- ibex_sca_register_file_write_batch_fvsr
- ibex_sca_register_file_write_batch_random
- ibex_sca_register_file_write_fvsr
- ibex_sca_register_file_write_random
- ibex_sca_register_file_read_batch_fvsr
- ibex_sca_register_file_read_batch_random
- ibex_sca_register_file_read_fvsr
The device code is located in lowRISC/opentitan#22272
=> [capture] Batch mode for Ibex SCA

capture/capture_hmac.py, capture/configs/hmac_sca_chip.yaml, capture/configs/hmac_sca_cw310.yaml, fault_injection/configs/pen.global_fi.ibex.char.sram_static.cw310.yaml, objs/sca_ujson_fpga_cw310.bin, target/communication/sca_hmac_commands.py
This commit adds the possiblility of capturing traces when a HMAC operation is performed. Note that on the device, HMAC from the cryptolib is used.
The device code is located in lowRISC/opentitan#22427
=> [capture] Add HMAC SCA

capture/capture_aes.py, capture/capture_ibex.py, capture/capture_kmac.py, capture/capture_sha3.py, fault_injection/fi_ibex.py, fault_injection/fi_otbn.py, objs/sca_ujson_fpga_cw310.bin, target/communication/fi_ibex_commands.py, target/communication/fi_otbn_commands.py, target/communication/sca_aes_commands.py, target/communication/sca_ibex_commands.py, target/communication/sca_kmac_commands.py, target/communication/sca_sha3_commands.py
This commit reads the device identifier from the target, which is transmitted after issuing a init command.
=> Read device ID from target

fault_injection/configs/pen.global_fi.ibex.char.sram_write_static.cw310.yaml, target/communication/fi_ibex_commands.py
This commit adds the handler for the ibex.char.sram_write_static test.
=> [fi] Add SRAM Write Static Test

fault_injection/configs/pen.global_fi.crypto.shadow_reg_access.cw310.yaml, target/communication/fi_crypto_commands.py
@nasahlpa 
Test added in OT FW in https://github.com/nasahlpa/opentitan/commit/1125e6def58c2a1c94d82945850ddec1fe97bc54
`.yaml` file created as best effort. Not tested as our setups run differently.
=> [fi] Add crypto_shadow_reg_access

fault_injection/configs/pen.global_fi.ibex.char.hardened_check_eq_unimps.cw310.yaml, target/communication/fi_ibex_commands.py
This commit adds the command handler for the
fi.ibex.char.hardened_check_eq_unimps test.
=> [fi] Add hardened check test
